version: '3.8'
services:
  web:
    build: web
    ports: 
      - "80:80"
    networks:
      - internal
  api:
    build: node-api
    networks:
      - internal
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.11
    networks:
      - internal
    volumes:
      - db-data

networks:
  internal:
volumes:
  db-data: