version: '3.8'
services:
  web:
    build: web
    container_name: web
    ports: 
      - "80:80"
    networks:
      - internal
    depends_on:
      - api
  api:
    build: node-api
    container_name: api
    networks:
      - internal
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.11
    container_name: mongo
    networks:
      - internal

networks:
  internal: