name: CI

on:
  push:
    branches: [ master ]
    tags: [ v* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      
    - uses: actions/checkout@v2
    - name: Build the API image
      run: docker build ./node-api --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/mean-template-api:latest
      
    - name: Build the Web image
      run: docker build ./web --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/mean-template-web:latest
